### ISSUE TITLE
Use with Laravel Scheduler

### ISSUE THREAD

**Issue by twd3** [aerni/laravel-sync#10]
Thank you for this, it's exactly what I was looking for. I'm going to be using this with Laravel Scheduler (assuming it works) but I'm confused about how the syntax would go. Do you know if it would be like this? Specifically this: artisan:sync:pull:production:content --no-interaction

```$schedule->command('artisan:sync:pull:production:content --no-interaction')->weekdays()->dailyAt('03:00')->timezone('America/Denver');```

**Comment by aerni** [comment]
Have you read the [docs on task scheduling](https://laravel.com/docs/11.x/scheduling#scheduling-artisan-commands)?

I think this should work:

```php
$schedule->command('sync pull production content --no-interaction')
    ->weekdays()
    ->dailyAt('03:00')
    ->timezone('America/Denver');
```

**Comment by twd3** [comment]
Yeah, that's the thing, I have read those docs and I'm still confused. Mainly because I'm already using scheduler for git commits and that looks like this: ```->command('statamic:git:commit')```. I know the other settings are right I'm just confused about the command syntax, again because this working git command has the colon's. I'll try to test. Closing because this isn't an issue just a question. Thanks again!
