### ISSUE TITLE
Issue pulling down from production

### ISSUE THREAD

**Issue by sjclark** [aerni/laravel-sync#5]
Having an unusual issue I can't quite narrow down.

I have a very simple config:
```php
  'remotes' => [

    'production' => [
      'user' => 'ploi',
      'host' => '192.192.192.192',
      'port' => 22,
      'root' => '/home/ploi/site.life',
      'read_only' => true,
    ],

  ],
``` 
(actual details replaced above, but correctly auths)
```php
  'recipes' => [

    'assets' => ['/public/assets/'],

  ],
  ```
  ```php
    'options' => [
    // '--archive',
    // '--itemize-changes',
    '--verbose',
    '--human-readable',
    '--progress'
  ],
  ```
  When running `php artisan sync pull production assets` I get:
  ```
   Please confirm that you want to pull the assets from production (yes/no) [yes]:
 > yes

skipping directory .

sent 8 bytes  received 13 bytes  14.00 bytes/sec
total size is 0  speedup is 0.00
The sync was successful
```
I've tried changing folders (same result), testing with a folder that doesn't exist (error saying folder doesn't exist). As far as I can tell everything works completely fine **except** the folder is skipped?

Not too sure what could be the culprit here?

**Comment by sjclark** [comment]
I can confirm that running
`rsync -avz -e ssh ploi@192.192.192.192:/home/ploi/site.life/public/assets /Users/sam/Desktop/test`
manually works correctly

**Comment by aerni** [comment]
What's the output of `php artisan sync:commands pull production assets`? This lists the commands to be executed.
