### ISSUE TITLE
Handling deleted assets?

### ISSUE THREAD

**Issue by stephenmeehanuk** [aerni/laravel-sync#6]
Hi

I'm a new user! Very happy with laravel-sync

Just wondering, if there's a way to keep track of deleted images?

My client deletes a bunch of images and uploads a bunch more on the staging server.

During development I add a few images locally.

Using `php artisan sync pull local assets` pulls all the new images from the staging server, which is great.

However, the images the cilent deleted are still on my local version of the site. When I run `php artisan sync push production assets`. All my new images and the old images the client deleted are pushed up to the staging server.

Is there anyway around this?

**Comment by aerni** [comment]
Rsync has a `--delete` option that should do what you want. Try this with a test folder: 
`php artisan sync pull local assets --option=--delete`

Here's a list of all the available rsync options for reference: https://ss64.com/bash/rsync_options.html

**Comment by stephenmeehanuk** [comment]
Thanks for the quick reply.

When using this command
```
php artisan sync pull local assets  --option=--delete 
```

I get this message:
```
rsync: --delete does not work without -r or -d.
```
If I add ` --option=-r ` it works :)
```
php artisan sync pull local assets  --option=--delete --option=-r 
```

But I can't seem to get the `--dry` run option to work? Is it not compatible?

I've tried this
```
php artisan sync pull local assets --dry --option=--delete --option=-r
``` 
and this
```
php artisan sync pull local assets  --option=--delete --option=-r --option=-n 
```
According to the docs `-n` "This makes rsync perform a trial run that doesn't make any changes"

Using either of these commands (with dry) doesn't appear to work, it doesn't error, it shows a `The sync was successful` message.

I've ran these on a test site, but I'd like to run a dry run if possible on other sites.

**Comment by aerni** [comment]
Sorry, no idea. The `--dry` flag simply adds the rsync `--dry-run` to the command. I'm not super familiar with all the rsync options and gotchas. So I can't be of much help here. Your questions are really related to rsync and not this package. I'm sure you can find an answer on Google or asking ChatGPT. Wishing you good luck!

**Comment by stephenmeehanuk** [comment]
Ok, no worries. I'll post back here if I find an answer, might be of use in the future. Thanks again :)
