### ISSUE TITLE
Implement --force option

### ISSUE THREAD

**Issue by CedsTrash** [aerni/laravel-sync#9]
I created a custom utility in Statamic for our customers to be able to push content themselves, by clicking a button.

This action triggers `Artisan::call('sync push production content')` but it doesn't seem to work as I'm guessing the command awaits confirmation.

Would it be possible to add a --force parameter, in order to bypass the confirmation?

**Comment by aerni** [comment]
You can use the `--no-interaction` flag to bypass the confirmation.
